### ISSUE TITLE
Support new csproj format projects.

### ISSUE THREAD

**Issue by alexdrl** [rsuter/ProjectDependencyBrowser#3]
Hello, we tried to use this promising tool to analyse dependencies in our projects, but found that the tool does not work for .NET Standard .csproj files.

Is there any interest in the community for this? Any alternative? 

Thanks.

**Comment by RicoSuter** [comment]
Hi, 

I think it should be relatively simple to implement this. The problem is that I have some other tools for which I have to add support .NET Standard support and which are more important to me (e.g. https://github.com/rsuter/NuGetReferenceSwitcher).

**Comment by RicoSuter** [comment]
Ok it was simple... v2.0.0 now supports .NET Standard. Please test and report any problems.

**Comment by alexdrl** [comment]
Wow, so fast. We tried it and it was working correctly... Thank you! 😄
